# Generated by Django 2.1.7 on 2019-05-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='flag',
            field=models.CharField(max_length=200),
        ),
    ]
